
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://naffgvxpxqfhqiopvkwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hZmZndnhweHFmaHFpb3B2a3dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NjI5MDAsImV4cCI6MjA2NjQzODkwMH0.AvfLVJnNuB29iaaoJSvnmpYLqSaRCmuGt3-JclbEi4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: sessionStorage, // Use sessionStorage instead of localStorage
    persistSession: true,
    autoRefreshToken: true,
  }
});
